# Generated by Django 4.0.1 on 2025-09-22 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('player equipment', 'Player Equipment'), ('training and match gear', 'Training & Match Gear'), ('fan merchandise', 'Fan Merchandise'), ('footwear and apparel accessories', 'footwear & apparel accessories'), ('Maintenance and care', 'Maintenance & Care'), ('Lifestyle and Casual', 'Lifestyle & Casual')], default='update', max_length=40)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
