# Generated by Django 4.0.1 on 2025-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_views',
        ),
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('player equipment', 'Player Equipment'), ('training and match gear', 'Training & Match Gear'), ('fan merchandise', 'Fan Merchandise'), ('footwear and apparel accessories', 'footwear & apparel accessories'), ('Maintenance and care', 'Maintenance & Care'), ('Lifestyle and Casual', 'Lifestyle & Casual')], default='update', max_length=40),
        ),
    ]
