# Generated by Django 4.0.1 on 2025-09-16 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_news_views_news_price_news_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('player equipment', 'Player Equipment'), ('training and match gear', 'Training & Match Gear'), ('fan merchandise', 'Fan Merchandise'), ('footwear and apparel accessories', 'footwear & apparel accessories'), ('Maintenance and care', 'Maintenance & Care'), ('Lifestyle and Casual', 'Lifestyle & Casual')], default='update', max_length=40)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sold', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
