# Generated by Django 4.0.1 on 2025-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(default='https://sdmntprnorthcentralus.oaiusercontent.com/files/00000000-3b10-622f-ac56-9a6bc8b4b16f/raw?se=2025-09-16T15%3A23%3A09Z&sp=r&sv=2024-08-04&sr=b&scid=499da52a-07bc-522c-8b89-3ee00b879922&skoid=e9d2f8b1-028a-4cff-8eb1-d0e66fbefcca&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-09-16T13%3A36%3A41Z&ske=2025-09-17T13%3A36%3A41Z&sks=b&skv=2024-08-04&sig=hHkJlreh%2B5r3rTuhD5QJ213%2BjvxlMvc7WKo4zwObcaU%3D'),
        ),
    ]
